version: "3.8"
services:
  book_catalog:
    build: ./book_catalog
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://librarypart04_user:14ZHDDoVsB6dznjFQRec30K5s6uKJo8O@dpg-crioostumphs73co0f6g-a.oregon-postgres.render.com/librarypart04

  inventory_management:
    build: ./inventory_management
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://librarypart04_user:14ZHDDoVsB6dznjFQRec30K5s6uKJo8O@dpg-crioostumphs73co0f6g-a.oregon-postgres.render.com/librarypart04
